services:
  postgres:
    container_name: postgres
    image: postgres:14.12-alpine
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./environment-files/key-cloak/.env
    networks:
      - local
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    links:
      - postgres
    ports:
      - "9000:8080"
    env_file:
      - ./environment-files/key-cloak/.env
    networks:
      - local
  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./environment-files/redis/.env
volumes:
  redis-data:
networks:
  local:
