server:
  port: 9090
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY-CLOAK-SERVER-URL}/realms/${KEY-CLOAK-REALM}
  cloud:
    gateway:
      routes:
        - id: profile
          uri: ${PROFILE-SERVICE-URL}
          predicates:
            - Path=/api/profile/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth
          uri: ${PROFILE-SERVICE-URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: media
          uri: ${MEDIA-SERVICE-URL}
          predicates:
            - Path=/api/media/**
          filters:
            - RemoveRequestHeader=Cookie
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0].name: Profile Service
    urls[0].url: /aggregate/profile-service/v3/api-docs
    urls[1].name: Media Service
    urls[1].url: /aggregate/media-service/v3/api-docs
  api-docs:
    path: /api-docs
servers:
  profile:
    url: ${PROFILE-SERVICE-URL}
  media:
    url: ${MEDIA-SERVICE-URL}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG