server:
  port: 8000
spring:
  application:
    name: profile
  kafka:
    bootstrap-servers: ${KAFKA-SERVER-URL}
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${KAFKA-REGISTRY.URL}
  data:
    redis:
      host: ${REDIS-HOST-URL}
      port: ${REDIS-PORT}
      password: ${REDIS-PASSWORD}
keycloak:
  clientId: ${KEY-CLOAK-CLIENT-ID}
  clientSecret: ${KEY-CLOAK-SECRET}
  grantType: client_credentials
  realm: ${KEY-CLOAK-REALM}
  serverUrl: ${KEY-CLOAK-SERVER-URL}
kafka:
  schema-folder-path: "/kafka/topic_schema/"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
